// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfXyiIPkqUp2hN6iC3E4m9oTZ3pkAnGtI',
    appId: '1:445872861062:web:e79c8310f90fa6a1920607',
    messagingSenderId: '445872861062',
    projectId: 'tp-poject',
    authDomain: 'tp-poject.firebaseapp.com',
    storageBucket: 'tp-poject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFTYn1KGagze3_dYS_FrhZg4MPJttWglw',
    appId: '1:445872861062:android:8242fd33a9a596f0920607',
    messagingSenderId: '445872861062',
    projectId: 'tp-poject',
    storageBucket: 'tp-poject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfr8wN-KMIpI0SAhtckHN50hlWcEWV2dI',
    appId: '1:445872861062:ios:2bef1ee4a12a92e3920607',
    messagingSenderId: '445872861062',
    projectId: 'tp-poject',
    storageBucket: 'tp-poject.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfr8wN-KMIpI0SAhtckHN50hlWcEWV2dI',
    appId: '1:445872861062:ios:e80d65baf0d164f2920607',
    messagingSenderId: '445872861062',
    projectId: 'tp-poject',
    storageBucket: 'tp-poject.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
