class LocationExceptionFailedToGetLocation implements Exception{}
class LocationExceptionFailedToSendLocation implements Exception{}
class LocationExceptionFailedToRecieveLocation implements Exception{}